from datetime import datetime
from pathlib import Path

from google.adk.tools import FunctionTool

REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)

def save_incident_report(
    incident_id:          str,
    timeline:             str,
    affected_assets:      str,
    threat_intel_summary: str,
    log_correlation:      str,
    geolocation:          str,
    containment_actions:  str,
    follow_up_steps:      str
) -> dict:
    """
    Generate and save a structured text incident report.

    Args:
        incident_id:          Unique identifier for this incident
        timeline:             Chronological sequence of events
        affected_assets:      Hosts, IPs, services affected
        threat_intel_summary: AbuseIPDB results and threat context
        log_correlation:      Historical pattern data from correlation agent
        geolocation:          Geographic info about source IP
        containment_actions:  What actions were taken and results
        follow_up_steps:      Recommended next steps

    Returns:
        dict with file path and confirmation
    """
    timestamp = datetime.now()
    filename = REPORTS_DIR / f"incident_{incident_id}_{timestamp.strftime('%Y%m%d_%H%M%S')}.txt"

    report = f"""Incident Report - {incident_id}
Generated: {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
Status: Containment Complete

==================== Incident Timeline ====================
{timeline}

==================== Affected Assets ====================
{affected_assets}

==================== Threat Intelligence Summary ====================
{threat_intel_summary}

==================== Log Correlation History ====================
{log_correlation}

==================== Geolocation of Source IP ====================
{geolocation}

==================== Containment Actions Taken ====================
{containment_actions}

==================== Recommended Follow-Up Steps ====================
{follow_up_steps}

Report auto-generated by Security MAS Reporting Agent
"""

    filename.write_text(report, encoding="utf-8")

    return {
        "success":   True,
        "file_path": str(filename),
        "report_id": incident_id,
        "timestamp": timestamp.isoformat()
    }

reporting_tool = FunctionTool(func=save_incident_report)